---
title: "Experience"
output: 
  html_document
---

<br>

## Education

<p style="text-align:left;">
    **Columbia University in the City of New York**
    <span style="float:right;">
    New York City, United States
    </span>
</p>

<p style="text-align:left;">
    **_Master of Public Health (MPH)_**, Environmental Health Sciences
    <span style="float:right;">
    September 2021 - May 2023
    </span>
</p>

*   GPA: 4.26/4.0

*   Certificate in Applied Biostatistics and Public Health Data Science

*   Relevant Courses: Analysis of Environmental Health Data, Analysis of Categorical Data, Applied Regression, Data Science, Statistical Computing with SAS, Relational Databases and SQL Programming for Research and Data Science, Fundamentals of Toxicology

<p style="text-align:left;">
    **China Agricultural University**
    <span style="float:right;">
    Beijing, China
    </span>
</p>

<p style="text-align:left;">
    **_Bachelor of Engineering (BEng)_**, Food Quality and Safety
    <span style="float:right;">
    September 2016 - June 2020
    </span>
</p>

*   GPA: 3.8/4.0

*   Relevant Courses: Biochemistry, Biostatistics and Experiment Design, Food Analysis, Food Hygiene and Safety Control, Food Toxicology, Fundamental Nutrition

<br>

## Work

<p style="text-align:left;">
    **Columbia University in the City of New York**
    <span style="float:right;">
    New York City, United States
    </span>
</p>

<p style="text-align:left;">
    **_Research Worker, Department of Environmental Health Sciences_**
    <span style="float:right;">
    May 2022 - Present
    </span>
</p>

*   Project name: Metal Exposure and Early Cardiovascular Risk in Adult E-Cigarette Users (VapeScan Longitudinal Study)

*   Generated description statistics and summary tables for VapeScan study and correspondingly updated reports every other week for guidance on subsequent recruiting participants

*   Performed statistical analyses, including linear regression, logistic regression, and linear mixed effects regression, on large datasets for VapeScan main study and sub-studies related to cannabis usage, mental health, spirometry measurements, blood and urinary metals measurements, and animal behavior experiments

*   Built and managed research databases of over 400 participants for each study visit and lab measurements to ensure accuracy and completeness of data

*   Developed comprehensive codebooks for databases to be used by research teams

*   Provided backup support on data analysis and visualizations to research teams for abstract preparations and periodical progress reports  

<br>

## Internship

<p style="text-align:left;">
    **Columbia University in the City of New York**
    <span style="float:right;">
    New York City, United States
    </span>
</p>

<p style="text-align:left;">
    **_Graduate Teaching Assistant, Department of Biostatistics_**
    <span style="float:right;">
    January 2023 - May 2023
    </span>
</p>

*   Course: Analysis of Categorical Data

*   Collaborated with 10 TAs and 1 Professor to review and provide feedback on weekly assignments to improve students' learning in a timely manner

*   Piloted for periodical exams and provided suggestion on revision in terms of examination questions

*   Held weekly office hours to provide customized assistance to meet individual needs   

*   Responsible for solving any course-related issues for a pre-assigned group of 20 students via email   

<p style="text-align:left;">
    **Beijing Sangao Yongxin Intellectual Property Agency Co., Ltd**
    <span style="float:right;">
    Beijing, China
    </span>
</p>

<p style="text-align:left;">
    **_Assistant Patent Agent, Department of Foreign Patent Affairs_**
    <span style="float:right;">
    August 2020 - February 2021
    </span>
</p>

*   Translated and proofread patent application documents for over 30 new cases

*   Conveyed examination Office Actions issued by the United States Patent and Trademark Office to inventors; advised on patent matters; communicated with collaborative foreign patent agency

*   Independently drafted response to Office Actions; replied to and corrected the application documents based on choices of inventors

<br>

## Research and Projects

<p style="text-align:left;">
    **Flight Delay and Cancellation Issue at John F. Kennedy International Airport**
    <span style="float:right;">
    October 2022 - December 2022
    </span>
</p>

*   Related Course: [Data Science I](https://p8105.com/), instructed by Jeff Goldsmith, Associate Professor in the Department of Biostatistics at Columbia University Mailman School of Public Health

*   Generated an interactive map of delay and cancellation cases for different destination airports by `leaflet` package in R, and made some interactive plots on outcome and exposures of interest by `plotly` package in R

*   Created a [Shiny App](https://sn2ylh-siyue-gao.shinyapps.io/delay_cancelation/) to display relationship between COVID cases and cancellation counts, delay counts and average delay times per day by `shiny` package in R

*   Explored relationship between flight on-time performance and predictors including airlines, weather conditions, types of delay, times of the day, and COVID daily cases, from 11/1/2021 to 1/31/2022, by building linear regression and Poisson regression models

*   Completed a project report, a screencast and a [website](https://yingchenx.github.io/final_project_jfk_delay/) as final deliverables

<p style="text-align:left;">
    **Motor Vehicle Collision Crash Frequency and Demographic Characteristics in NYC, 2020**
    <span style="float:right;">
    September 2022 - December 2022
    </span>
</p>

*   Related Course: Public Health GIS, instructed by Joel A. Capellan, Adjunct Assistant Professor in the Department of Environmental Health Sciences at Columbia University Mailman School of Public Health

*   Generated maps on motor vehicle collision crash risk and demographic characteristics distribution by zip code in New York City by `tmap`, `tmaptools`, `spgwr` packages in R and by QGIS

*   Conducted spatial clustering analysis of motor vehicle collision crash frequency by GeoDa and mapped out relevant results by QGIS

*   Completed a [poster](gis_project.html) with Background, Methods, Results, Discussions, and Conclusions as a final deliverable

<p style="text-align:left;">
    **Arsenic and Related Effects on Cardiovascular Disease**
    <span style="float:right;">
    February 2022 - April 2022
    </span>
</p>

*   Faculty Mentor: Anne Nigra, Assistant Professor in the Department of Environmental Health Sciences at Columbia University Mailman School of Public Health

*   Performed literature reviews on arsenic exposure and its related effects on cardiovascular disease, including impact of different doses of exposure, current findings in occupational studies, and management options for harm reduction

*   Completed a 2,600-word research paper

<p style="text-align:left;">
    **Construction of Chondroitin Sulfate Biosensor**
    <span style="float:right;">
    May 2018 - May 2019
    </span>
</p>

*   Faculty Mentor: Zhiyi Yao, Associate Professor in the College of Food Science and Nutritional Engineering at China Agricultural University

*   Conducted lab experiments to develop a novel chondroitin sulfate fluorescent biosensor, including sample preparation, linear response range verification, sensitivity and specificity identification, and real-world application in commercial products

*   Analyzed program statistics and created data visualization for final publication, including graphs and charts, by Origin

<br>

## Skills

*   Proficient knowledge in MS Office (Word, Excel, PowerPoint)

*   Proficient knowledge in R, SAS, MySQL, QGIS, GeoDa

*   Intermediate knowledge in SPSS, Origin

*   Native in Chinese

*   Fluent in English
